[tool.poetry]
name = "chat"
version = "0.2.0"
description = "RAG ChatBot"
authors = ["Umberto Griffo <umberto.griffo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
tqdm = "~=4.65.0"
requests = "~=2.31.0"
numpy = "~=1.24.2"
sentencepiece = "~=0.1.99"
langchain = "~=0.0.341"
pyllamacpp = "==1.0.7"
gpt4all = "==2.0.2"
streamlit = "~=1.29.0"
unstructured = "==0.7.7"
chromadb = "~=0.4.18"
transformers = "~=4.33.0"
ctransformers = { version = "~=0.2.27", extras = ["cuda"] }
rich = "~=13.4.2"
pyfiglet = "~=0.7"
clean-text = "~=0.6.0"
Unidecode = "~=1.3.6"
nest_asyncio = "~=1.5.8"

[tool.poetry.group.dev.dependencies]
pytest = "~=7.2.1"
pytest-cov = "~=4.0.0"
pytest-mock = "~=3.10.0"
pre-commit = "~=3.1.0"
black = "~=23.1.0"
isort = "~=5.12.0"
flake8 = "~=6.0.0"
httpx = "~=0.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
