[tool.poetry]
name = "chat"
version = "0.1.0"
description = "Local ChatBot with GPT4All, LangChain and Chroma"
authors = ["Umberto Griffo <umberto.griffo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.5"
tqdm = "~=4.65.0"
requests = "~=2.31.0"
numpy = "~=1.24.2"
sentencepiece = "~=0.1.99"
langchain = "^0.0.215"
pyllamacpp = "==1.0.7"
gpt4all = "==0.3.5"
unstructured = "==0.7.7"
chromadb = "~=0.3.26"
transformers = "~=4.30.2"
rich = "~=13.4.2"
clean-text = "~=0.6.0"
sentence-transformers = "~=2.2.2"
Unidecode = "~=1.3.6"

[tool.poetry.group.dev.dependencies]
pytest = "~=7.2.1"
pytest-cov = "~=4.0.0"
pytest-mock = "~=3.10.0"
pre-commit = "~=3.1.0"
black = "~=23.1.0"
isort = "~=5.12.0"
flake8 = "~=6.0.0"
httpx = "~=0.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
