name: CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]


jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.0
          virtualenvs-in-project: true

      - name: Setup environment
        run: |
          poetry lock --check
          poetry install --no-root --no-ansi
          . .venv/bin/activate && pip3 install sentence-transformers~=2.2.2
          . .venv/bin/activate && pip3 install llama-cpp-python~=0.2.23

      - name: Run tests
        run: |
          poetry run pytest -v
